Repository codestates-seb/seb44_main_001, pull requests merged in 2023-07, with the labels that each got.

#25 [FE] Chore: 컴포넌트파일생성과 아이콘 이미지 다운
  client/src/common/assets/icons/cancle.svg
  client/src/common/assets/icons/culture.svg
  client/src/common/assets/icons/etc.svg
  client/src/common/assets/icons/food.svg
  client/src/common/assets/icons/game.svg
  client/src/common/assets/icons/music.svg
  client/src/common/assets/icons/pet.svg
  client/src/common/assets/icons/search.svg
  client/src/common/assets/icons/sports.svg
  client/src/common/assets/icons/study.svg
  client/src/common/style.ts
  client/src/pages/Lists/components/CategoryIcons.tsx
  client/src/pages/Lists/components/SearchBar.tsx
  client/src/pages/Lists/views/Lists.tsx
Labels: 상, FE

#30 [BE] 비밀번호 인코딩, 로그인
  server/momo/build.gradle
  server/momo/src/main/java/com/momo/config/SecurityConfig.java
  server/momo/src/main/java/com/momo/member/controller/MemberController.java
  server/momo/src/main/java/com/momo/member/dto/MemberPatchDto.java
  server/momo/src/main/java/com/momo/member/dto/MemberPostDto.java
  server/momo/src/main/java/com/momo/member/dto/MemberResponseDto.java
  server/momo/src/main/java/com/momo/member/entity/Member.java
  server/momo/src/main/java/com/momo/member/repository/MemberRepository.java
  server/momo/src/main/java/com/momo/member/service/MemberDetailsService.java
  server/momo/src/main/java/com/momo/member/service/MemberService.java
Labels: BE, 상

#36 [BE]게시판,카테고리 리펙토링
  server/momo/build.gradle
  server/momo/src/main/java/com/momo/category/controller/CategoryController.java
  server/momo/src/main/java/com/momo/category/dto/CategoryPatchDto.java
  server/momo/src/main/java/com/momo/category/dto/CategoryPostDto.java
  server/momo/src/main/java/com/momo/category/dto/CategoryResponseDto.java
  server/momo/src/main/java/com/momo/category/entity/Category.java
  server/momo/src/main/java/com/momo/category/mapper/CategoryMapper.java
  server/momo/src/main/java/com/momo/category/repository/CategoryRepository.java
  server/momo/src/main/java/com/momo/category/service/CategoryService.java
  server/momo/src/main/java/com/momo/member/entity/Member.java
  server/momo/src/main/java/com/momo/member/service/MemberService.java
  server/momo/src/main/java/com/momo/post/controller/PostController.java
  server/momo/src/main/java/com/momo/post/dto/PostPatchDto.java
  server/momo/src/main/java/com/momo/post/dto/PostPostDto.java
  server/momo/src/main/java/com/momo/post/dto/PostResponseDto.java
  server/momo/src/main/java/com/momo/post/entity/Post.java
  server/momo/src/main/java/com/momo/post/mapper/PostMapper.java
  server/momo/src/main/java/com/momo/post/service/PostService.java
Labels: BE
